language: python
python: 3.5
sudo: false
cache:
  directories:
  - "~/.cache/pip"
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy
install:
  - pip install tox codecov
script:
  - tox -v
after_success:
  - codecov
